### ISSUE TITLE
Link to Google's Navigation Codelab is not active

### ISSUE THREAD

**Issue by ghost** [MarianVasilca/android-navigation-codelab#1]
Does somebody know why the link to Google's Navigation Codelab is deleted ? 
When you click on https://codelabs.developers.google.com/codelabs/android-navigation/ in your README file, then the destination is not reachable.

**Comment by MarianVasilca** [comment]
I have no idea why it's not working anymore. This is a fork from the original codelab posted in May 2018. 
You should the [official documentation](https://developer.android.com/guide/navigation) of the library if you want to learn more about it.
